[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["tainanpenning <tainanhartwigpenning@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
django = ">=6.0.4,<7.0.0"
djangorestframework = ">=3.17.1,<4.0.0"
psycopg2-binary = ">=2.9.12,<3.0.0"
django-cors-headers = ">=4.9.0,<5.0.0"
pillow = ">=12.2.0,<13.0.0"
django-extensions = ">=4.1,<5.0"
cloudinary = ">=1.44.2,<2.0.0"
python-dotenv = ">=1.2.2,<2.0.0"
djangorestframework-simplejwt = {extras = ["token-blacklist"], version = ">=5.5.1,<6.0.0"}

# faltavam no último exemplo
gunicorn = ">=26.0.0,<27.0.0"
whitenoise = ">=6.12.0,<7.0.0"
dj-database-url = ">=3.1.2,<4.0.0"

[tool.poetry.group.dev.dependencies]
pytest = ">=9.0.3,<10.0.0"
pytest-django = ">=4.7.0,<5.0.0"
factory-boy = ">=3.3.3,<4.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
